### ISSUE TITLE
出典シート作成

### ISSUE THREAD

**Issue by yuhi-dosei** [yowayowa-19/hacku-promotion#5]
出典記録シート
━━━━━━━━━━━━━━━━
プレゼン資料や作品で利用した画像・素材・OSSの一覧を「Hack U 出典記録シート」のフォーマットに記載して、プレゼン資料と一緒にサポーター宛に提出してください。
発表会はYouTube Liveで公開生放送されますので、資料や作品内で使われた画像や素材、ライセンスなどに問題がないかをこちらで確認します。
※シートはExcel形式です。もしExcelを持ってなくて記入できない場合はお知らせください。
　自作の素材は「自作」と書いてください。

▼Hack U 出典記録シート
https://yahoo.jp/fzxUJ1

**Comment by t4t5u0** [comment]
```
python = "3.10"
fastapi = "0.74.1" MIT
uvicorn = "0.17.5" BSD 3-Clause "New" or "Revised" License
psycopg2-binary = "2.9.3" GNU LESSER GENERAL PUBLIC LICENSE
```

```
PostgreSQL BSD or MIT
```

**Comment by t4t5u0** [comment]
[三条項BSDライセンス – プログラミングガイド by Ceed](https://ceed-web.net/programming/%E4%B8%89%E6%9D%A1%E9%A0%85bsd%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9/)
[GNU Lesser General Public License - Wikipedia](https://ja.wikipedia.org/wiki/GNU_Lesser_General_Public_License)

BSD 3-Clause "New" or "Revised" License は著作権・ライセンス表示義務がある

**Comment by materialofmouse** [comment]
Bluez 5.50 (http://www.bluez.org/release-of-bluez-5-50/) GPL
bluez-ibeacon (https://github.com/carsonmcdonald/bluez-ibeacon) MIT

**Comment by Atria64** [comment]
# Android概要
Android周りは基本Apache-2.0ライセンス系で統一されています。   
また、OSMについてはマップ内などに著作権表記が必要です(以下リンク参照)
# リンク
- OpenStreetMap 
     - [ライセンスとプライバシーポリシーについて | OpenStreetMap Japan](https://openstreetmap.jp/terms_and_privacy)
 - [square/okhttp: Square’s meticulous HTTP client for the JVM, Android, and GraalVM.](https://github.com/square/okhttp)
     - Apache-2.0 License
 - AltBeacon [android-beacon-library](https://github.com/AltBeacon/android-beacon-library)
     - Apache-2.0 License
 - [osmdroid/osmdroid: OpenStreetMap-Tools for Android](https://github.com/osmdroid/osmdroid)
     - Apache-2.0 License
 - Material Icons
     - [Material Icons Guide  |  Google Fonts  |  Google Developers](https://developers.google.com/fonts/docs/material_icons)
     - Apache-2.0 License

**Comment by yuhi-dosei** [comment]
暫定で出した
