### ISSUE TITLE
PV構成考える

### ISSUE THREAD

**Issue by yuhi-dosei** [yowayowa-19/hacku-promotion#7]

**Comment by yuhi-dosei** [comment]
発表時間すべて動画でも良いか聞く

**Comment by yuhi-dosei** [comment]
https://hackmd.io/@uDHYaH9RQvW3aEdxDli6yg/SJKliZrbc/edit
構成考えました。Googleのやつだとダジャレ的なセリフがすごく上手くてすっとはいってくるから
そういう言葉を充実させたい

レビューお願いします
@materialofmouse @t4t5u0 @Atria64 @HiromuYoshida

**Comment by materialofmouse** [comment]
> アフリカでは1分間に60秒が経過していて、たくさんの人間があくびをしています。

面白くていいと思う！
アフリカのジョークとてもいいと思うけど、世界を超えると言っているため、もうちょっと別のジョークのほうがいいかなと思う。

アフリカの下りを消して、「世界では、今現在もたくさんの人間があくびをしています。」みたいなナレーションで、映像を世界各国の首都で、人々が歩いている。みたいな壮大な映像を裏で流しておく。みたいな方が面白いかなと思った。

ただコレに関してはちょっと細かすぎなのと、あくまで僕の感想なのでこのままでも問題はないです！

**Comment by materialofmouse** [comment]
結びの言葉の
> 100年に一度と言われた、前作を超える出来栄え(だと思います)。
> 我々人類にとって、大きな一歩だと思います。

は前作をAHCHOOに置き換えていいと思う。
あと、100年に一度よりも「衝撃のスタートアップを切った」みたいに、前作との関係性を強くしたほうが面白いと感じた！

**Comment by yuhi-dosei** [comment]
世界の映像、権利関係考えると 5人それぞれのあくびを撮って それを透過しながら地球の映像が流れるみたいなのがいいかな

衝撃のスタートアップを切っためちゃくちゃ良い

特にハードの部分なんだけどもうちょいダジャレ的な言葉を増やしたくてそこの部分意見ほしいです！

**Comment by materialofmouse** [comment]
ハードの部分なんだけど、今の内容は機能とかを説明してるから、もうちょっとジョークとかそういうのを入れたいって感じだよね。

ここに関して今パッと思いついたのは。

**同意できる要素を取り入れる**
例えば、あくび出たときにスマホ取り出してボタンを押すと、タイミングがずれてしまう(もうちょっと早く押せてればコンボつながってたのに、、、)
みたいな問題を解決できます！
「より素早く、よりスマートに」
みたいな感じで、こういう困ったことがあるからハードを作ったよ。っていう説得力のある説明にする。

ジョークに関しては思いついてないからもうちょっと考える
